### PR TITLE
misc-fixes

### LINKED ISSUE #255: Unnecessary scroll bars
scroll

### PR DESCRIPTION
**Pull request by TristanWright**
fix(css): closes #255 Unnecessary scroll bars on split views
The height of the nav bars are each 2.4, the font size of the nav bars are 1.05. font-size 1 would
not add any height to a component whose height is already defined. So 2.4 + 2.4 + 0.05 + 0.05 = 4.9em, thus `height: calc(100vh - 4.9em)`

### CODE REVIEW

**Comment by TristanWright** [comment]
Not ready to be merged, getting a funny server error when I try to change the status.
screen shot 2016-03-18 at 18 01 28

**Comment by cjh1** [comment]
What are the steps that result in this message?

**Comment by jourdain** [comment]
I think Tristan was trying to update the status of a simulation using some endpoint.

File: src/workflows/pyfr/common/steps/Simulation/Start/index.js [hunk 1]
```diff
@@ -112,6 +112,7 @@ export default React.createClass({
       .then((resp) =>
         client.updateSimulationStep(this.props.simulation._id, 'Simulation', {
           view: 'run',
+          status: 'running',
```
Comment (TristanWright) [inline src/workflows/pyfr/common/steps/Simulation/Start/index.js]: Right here, trying to update the state of the simulation step.

Comment (cjh1) [inline src/workflows/pyfr/common/steps/Simulation/Start/index.js]: So the supported step statuses are enforce here:

https://github.com/Kitware/HPCCloud/blob/master/server/hpccloud/server/models/definitions.json#L61

If you want the add the 'running' state then it will need to be added to this list.

Comment (TristanWright) [inline src/workflows/pyfr/common/steps/Simulation/Start/index.js]: I'm moving status to the top metadata object instead of having it per step

**Comment by TristanWright** [comment]
Will merge when travis completes.
